---
# Default values for sjr.
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: ghcr.io/snapp-incubator/stan-js-replicator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

service:
  type: ClusterIP

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

serviceMonitor:
  enabled: false

logger:
  level: "info"
  syslog:
    enabled: "false"
    network: "tcp"
    tag: "saf"
    address: "127.0.0.1:9000"

nats:
  url: "nats://nats:4222"

streaming:
  url: "nats://nats:4222"
  clusterid: "snapp"
  group: "sjr"

telemetry:
  trace:
    enabled: "false"
    agent:
      host: "127.0.0.1"
      port: "6831"
  profiler:
    enabled: "false"
    address: "http://127.0.0.1:4040"

channel: koochooloo

topics:
  - k.1
  - k.2

stream:
  maxage: 1h
  replicas: 1
  storagetype: 1
