---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sjr.fullname" . }}
  labels:
    {{- include "sjr.labels" . | nindent 4 }}
data:
  config.yaml: |
    monitoring:
      enabled: true
      address: ":8080"
    {{ with .Values.nats }}
    output:
      {{ toYaml . | nindent 6 }}
    {{ end }}
    {{ with .Values.logger }}
    logger:
      {{ toYaml . | nindent 6 }}
    {{ end }}
    {{ with .Values.telemetry }}
    telemetry:
      {{ toYaml . | nindent 6 }}
    {{ end }}
    {{ with .Values.input }}
    input:
      {{ toYaml . | nindent 6 }}
    {{ end }}
    channel: {{ .Values.channel }}
    {{ with .Values.topics }}
    topics:
      {{ range $name := . }}
        - {{ $name }}
      {{ end }}
    {{ end }}
    {{ with .Values.stream }}
    stream:
      {{ toYaml . | nindent 6 }}
    {{ end }}
