apiVersion: v1
kind: Service
metadata:
  name: {{ include "sjr.fullname" . }}
  labels:
    {{- include "sjr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: monitor
      protocol: TCP
      name: monitor
  selector:
    {{- include "sjr.selectorLabels" . | nindent 4 }}
