---
monitoring:
  enabled: true
  address: ":8080"
output:
  url: "nats://127.0.0.1:4222"
logger:
telemetry:
input:
  group: "sjr"
  nats:
    url: "nats://127.0.0.1:4222"
  streaming:
    url: "nats://127.0.0.1:4222"
    clientid: "snapp"
channel: "koochooloo"
topics:
  - k.1
  - k.2
stream:
  maxage: "1h"
  storagetype: 1
  replicas: 1
